services:
  garage:
    image: dxflrs/garage:v2.3.0
    network_mode: "host"
    restart: unless-stopped
    build: "./garage/"
    volumes:
      - ./garage/garage.toml:/etc/garage.toml
      - ./garage/meta:/var/lib/garage/meta
      - ./garage/data:/var/lib/garage/data
    ports:
      - "3900:3900"
    #env_file: "garage.env"

  db:
    image: postgres
    restart: always
    shm_size: 512mb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/18/docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tmz
      POSTGRES_DB: tmz_pp

  frontend:
    depends_on: 
      - backend
    build: ./frontend/
    ports:
      - "5173:5173"

  backend:
    depends_on: 
      - db
    build: ./backend/
    ports:
      - "3000:3000"

volumes:
  db-data:
